apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "ganescluster4-b016"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "ganescluster4-b016"
    spec:
      containers:
        - name: "ganescluster4-b016"
          image: "ganesacr.azurecr.io/ganescluster4"
          ports:
          - containerPort: 80