apiVersion: v1
kind: Service
metadata:
    name: "ganescluster4-b016"
    labels:
        app: "ganescluster4-b016"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "ganescluster4-b016"