on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ganesacr.azurecr.io
        username: ${{ secrets.acr_ganesacr_username }}
        password: ${{ secrets.acr_ganesacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/nodebrady" -f  "nodebrady/Dockerfile" -t ganesacr.azurecr.io/ganescluster4:${{ github.sha }}
        docker push ganesacr.azurecr.io/ganescluster4:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_ganescluster4_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ganescluster4a6aa | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ganescluster4a6aa`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ganescluster4a6aa
        container-registry-url: ganesacr.azurecr.io
        container-registry-username: ${{ secrets.acr_ganesacr_username }}
        container-registry-password: ${{ secrets.acr_ganesacr_password }}
        secret-name: ganesclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: ganescluster4a6aa
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          ganesacr.azurecr.io/ganescluster4:${{ github.sha }}
        imagepullsecrets: |
          ganesclusterdockerauth